### ISSUE TITLE
Python / virtualenv not found in latest container

### ISSUE THREAD

**Issue by philmichel** [m0ngr31/genmon#2]
It seems like genmon has changed something in genmonmaint.sh since the containers were last built. Logs in the container show the following error:

```
using binary: /app/genmon/genenv/bin/python
Starting genmon python scripts
/app/genmon/startgenmon.sh: line 20: /app/genmon/genenv/bin/activate: No such file or directory
sudo: /app/genmon/genenv/bin/python: command not found
/app/genmon/startgenmon.sh: line 26: deactivate: command not found
```

The auto-build log on github complains that it can't find requirements.txt, so perhaps that's the issue - it is not installing genmon's python requirements?

```
#28 118.1 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Thanks for looking!

**Comment by m0ngr31** [comment]
I think I figured out the issue. Do you want to try the latest and see if it works for you?

**Comment by philmichel** [comment]
Working now! Thanks for the quick fix!
